/**
 * PRINCE FAVE MDX - A WhatsApp Bot
 * WSG (Would You Rather) Game
 * 
 * Copyright (c) 2025 C.O TECH
 * DO NOT COPY THIS CODE (works only for this bot)
 * Licensed under MIT
 * 
 * Credits:
 * - Baileys Library by @adiwajshing
 */

async function wsgCommand(sock, chatId, message) {
    // 300 "Would You Rather" questions
    const questions = [
        "Would you rather be invisible for a day or be able to fly for a day?",
        "Would you rather live without music or live without movies?",
        "Would you rather have the ability to teleport or read minds?",
        "Would you rather always be 10 minutes late or always be 20 minutes early?",
        "Would you rather never use social media again or never watch TV again?",
        "Would you rather lose your sight or lose your hearing?",
        "Would you rather have unlimited money or unlimited knowledge?",
        "Would you rather fight 1 horse-sized duck or 100 duck-sized horses?",
        "Would you rather always have bad breath or always have smelly feet?",
        "Would you rather live on the moon or live under the sea?",
        "Would you rather eat only pizza forever or eat only burgers forever?",
        "Would you rather be the funniest person in the room or the smartest?",
        "Would you rather travel to the past or the future?",
        "Would you rather live without internet or without AC/fan?",
        "Would you rather be able to talk to animals or speak every language?",
        "Would you rather never age physically or never age mentally?",
        "Would you rather always sing instead of talking or dance everywhere you go?",
        "Would you rather live in a mansion alone or a small house with your friends?",
        "Would you rather be famous but hated or unknown but loved?",
        "Would you rather only whisper forever or only shout forever?",
        "Would you rather never sleep again or never eat again?",
        "Would you rather have no phone or no friends?",
        "Would you rather always wear wet socks or never shower again?",
        "Would you rather live without laughter or without love?",
        "Would you rather drink only water or only soda for life?",
        "Would you rather be a child forever or an adult forever?",
        "Would you rather be rich but lonely or poor but loved?",
        "Would you rather have wings or a tail?",
        "Would you rather be a genius nobody knows or average and famous?",
        "Would you rather marry your first crush or your celebrity crush?",
        "Would you rather live in a video game world or in a cartoon world?",
        "Would you rather never be able to read or never be able to write?",
        "Would you rather have free WiFi everywhere or free food everywhere?",
        "Would you rather never get sick or never get tired?",
        "Would you rather have super strength or super speed?",
        "Would you rather know when you’ll die or how you’ll die?",
        "Would you rather lose your hair or lose your teeth?",
        "Would you rather be stuck in traffic or stuck with slow internet?",
        "Would you rather be rich and sad or poor and happy?",
        "Would you rather have unlimited clothes or unlimited gadgets?",
        "Would you rather never celebrate birthdays or never celebrate holidays?",
        "Would you rather be able to pause time or rewind time?",
        "Would you rather live in a desert or live in Antarctica?",
        "Would you rather forget your past or never make new memories?",
        "Would you rather be the hero or the villain?",
        "Would you rather be loved by all or feared by all?",
        "Would you rather always lose or never play games?",
        "Would you rather have a rewind button or a fast-forward button for life?",
        "Would you rather never speak again or never hear again?",
        "Would you rather own a private jet or a private island?",
        "Would you rather always eat cold food or always eat hot food?",
        "Would you rather be a famous actor or a famous musician?",
        "Would you rather be always hungry or always thirsty?",
        "Would you rather have 1 million followers or 1 million dollars?",
        "Would you rather be able to stop time or fly?",
        "Would you rather have a photographic memory or forget everything?",
        "Would you rather be the best at one thing or good at many things?",
        "Would you rather live in space or live underwater?",
        "Would you rather be Batman or Spider-Man?",
        "Would you rather live with no money or no happiness?",
        "Would you rather eat ice cream in winter or soup in summer?",
        "Would you rather always wear fancy clothes or always wear casual clothes?",
        "Would you rather play video games all day or watch movies all day?",
        "Would you rather win the lottery or live twice as long?",
        "Would you rather be able to breathe underwater or fly?",
        "Would you rather have a dog or a cat?",
        "Would you rather eat spicy food forever or bland food forever?",
        "Would you rather always be tired or always be bored?",
        "Would you rather live in a world without music or without books?",
        "Would you rather be invisible or immortal?",
        "Would you rather always be hot or always be cold?",
        "Would you rather be a king 500 years ago or an average person today?",
        "Would you rather never go outside again or never stay inside again?",
        "Would you rather have no emotions or too many emotions?",
        "Would you rather be remembered forever or live happily but be forgotten?",
        "Would you rather always talk in riddles or always sing?",
        "Would you rather eat chocolate forever or chips forever?",
        "Would you rather always be the center of attention or always be ignored?",
        "Would you rather have unlimited free travel or unlimited free shopping?",
        "Would you rather live without electricity or without water?",
        "Would you rather never use YouTube or never use WhatsApp?",
        "Would you rather be able to see ghosts or be one?",
        "Would you rather always laugh or always cry?",
        "Would you rather only be able to lie or only be able to tell the truth?",
        "Would you rather lose your phone or lose your wallet?",
        "Would you rather be a genius with no friends or average with many friends?",
        "Would you rather live in a haunted house or a house with no internet?",
        "Would you rather only eat sweet food or only salty food?",
        "Would you rather never get tired or never get bored?",
        "Would you rather marry someone rich but boring or poor but fun?",
        "Would you rather have super hearing or super sight?",
        "Would you rather never have exams or never have homework?",
        "Would you rather always be hungry or always be sleepy?",
        "Would you rather have 3 arms or 3 legs?",
        "Would you rather live without games or without movies?",
        "Would you rather be always rich but sad or poor but happy?",
        "Would you rather never brush your teeth or never shower?",
        "Would you rather be able to talk to plants or animals?",
        "Would you rather have your dream job or marry your dream partner?",
        "Would you rather live in winter forever or summer forever?",
        "Would you rather always be late or always be early?",
        "Would you rather eat one meal forever or try new food every day?",
        "Would you rather be able to see the future or change the past?",
        "Would you rather be a famous athlete or a famous scientist?",
        "Would you rather never celebrate your birthday or never celebrate Christmas?",
        "Would you rather live in a small house but happy or mansion but sad?",
        "Would you rather never talk again or never text again?",
        "Would you rather be good at sports or good at studies?",
        "Would you rather have no phone or no internet?",
        "Would you rather live in a world of cartoons or anime?",
        "Would you rather be always serious or always joking?",
        "Would you rather be stuck in a room with a clown or a snake?",
        "Would you rather eat raw food forever or burnt food forever?",
        "Would you rather play football or basketball forever?",
        "Would you rather have no friends or no family?",
        "Would you rather never play games or never listen to music?",
        "Would you rather have 1 wish come true or 10 wishes that may never come true?",
                "Would you rather spend your life on a boat or in a treehouse?",
        "Would you rather always rhyme when you speak or always sing?",
        "Would you rather be able to erase memories or add fake ones?",
        "Would you rather only eat breakfast food or only dinner food?",
        "Would you rather live forever or die tomorrow?",
        "Would you rather be stuck in a video game or a movie?",
        "Would you rather never use Google or never use YouTube?",
        "Would you rather have 10 siblings or be an only child?",
        "Would you rather only be able to whisper or only be able to scream?",
        "Would you rather be a wizard or a superhero?",
        "Would you rather always get stuck in traffic or always have slow Wi-Fi?",
        "Would you rather win $10,000 or let your best friend win $100,000?",
        "Would you rather fight a shark or a lion?",
        "Would you rather never laugh again or never cry again?",
        "Would you rather live without shoes or without a phone?",
        "Would you rather be the richest person or the smartest?",
        "Would you rather be famous on TikTok or YouTube?",
        "Would you rather live in a treehouse or a cave?",
        "Would you rather never age or never die?",
        "Would you rather eat only fruit or only vegetables?",
        "Would you rather live in the mountains or at the beach?",
        "Would you rather only wear black or only wear white?",
        "Would you rather be able to swim like a dolphin or climb like a monkey?",
        "Would you rather always have to dance everywhere you go or sing?",
        "Would you rather be the funniest person or the most serious?",
        "Would you rather be able to draw or to sing?",
        "Would you rather never eat sweets or never eat meat?",
        "Would you rather have no gravity or too much gravity?",
        "Would you rather never get wet in rain or never get hot in sun?",
        "Would you rather have a rewind button for your mistakes or a pause button?",
        "Would you rather be the leader or the follower?",
        "Would you rather only be able to text or only be able to call?",
        "Would you rather live one long boring life or many short exciting lives?",
        "Would you rather live in a city or a village?",
        "Would you rather never read again or never write again?",
        "Would you rather be able to remember everything or forget everything?",
        "Would you rather be able to live on Mars or the Moon?",
        "Would you rather always step on something wet or sticky?",
        "Would you rather be loved by everyone or feared by everyone?",
        "Would you rather never be able to smile or never be able to frown?",
        "Would you rather have a flying car or a talking robot?",
        "Would you rather be the youngest or the oldest sibling?",
        "Would you rather only watch horror movies or only watch comedy movies?",
        "Would you rather always wear glasses or never see clearly?",
        "Would you rather never play sports again or never watch sports again?",
        "Would you rather be able to talk to birds or fish?",
        "Would you rather have no school or no work?",
        "Would you rather always wear the same clothes or never repeat outfits?",
        "Would you rather marry a celebrity or your childhood crush?",
        "Would you rather only watch anime or only watch cartoons?",
        "Would you rather live with robots or with animals?",
        "Would you rather eat raw onions or raw garlic?",
        "Would you rather never go shopping again or never eat out again?",
        "Would you rather have no hair or too much hair?",
        "Would you rather always be hungry or always be sleepy?",
        "Would you rather have the power to heal or the power to fly?",
        "Would you rather live without hot water or cold water?",
        "Would you rather always be serious or always laugh?",
        "Would you rather own 100 cats or 100 dogs?",
        "Would you rather only talk in memes or only talk in emojis?",
        "Would you rather live without chocolate or without coffee?",
        "Would you rather never play video games or never use the internet?",
        "Would you rather only use Instagram or only use TikTok?",
        "Would you rather never brush your hair or never brush your teeth?",
        "Would you rather fight with a lion or a crocodile?",
        "Would you rather have the power of invisibility or immortality?",
        "Would you rather never feel pain or never feel fear?",
        "Would you rather always lose your wallet or your phone?",
        "Would you rather be a famous writer or a famous painter?",
        "Would you rather never stop talking or never talk again?",
        "Would you rather never forget a face or never forget a name?",
        "Would you rather have the fastest internet or unlimited free food?",
        "Would you rather eat ice cream every day or pizza every day?",
        "Would you rather live without shoes or without a bed?",
        "Would you rather never be able to lie or always lie?",
        "Would you rather own a dragon or a unicorn?",
        "Would you rather be able to sing beautifully or dance perfectly?",
        "Would you rather live in Harry Potter’s world or Marvel’s world?",
        "Would you rather never use WhatsApp or never use Instagram?",
        "Would you rather never see again or never hear again?",
        "Would you rather be rich but unhealthy or poor but healthy?",
        "Would you rather have no name or no face?",
        "Would you rather only listen to one song forever or one movie forever?",
        "Would you rather never get tired or never get bored?",
        "Would you rather have wings but never fly or a car but no fuel?",
        "Would you rather live with no family or no friends?",
        "Would you rather have 10 best friends or 1 soulmate?",
        "Would you rather always live in summer or always live in winter?",
        "Would you rather be trapped in a desert or on a snowy mountain?",
        "Would you rather always be cold or always be hot?",
        "Would you rather live with aliens or with robots?",
        "Would you rather live in a game forever or in a movie forever?",
        "Would you rather have super speed or super strength?",
        "Would you rather be rich but hated or poor but loved?",
        "Would you rather have magic powers or be super rich?",
        "Would you rather always run or always crawl?",
        "Would you rather always tell jokes or always listen?",
        "Would you rather never eat rice again or never eat bread again?",
        "Would you rather be famous in your country or in the world?",
        "Would you rather be always sleepy or always tired?",
        "Would you rather always smile or always frown?",
        "Would you rather be a vampire or a werewolf?"
    ];

    const randomQuestion = questions[Math.floor(Math.random() * questions.length)];

    // Read image from assets folder
    const imageBuffer = fs.readFileSync("../assets/wouldur.jpg"); // 

    // Send image + text
    await sock.sendMessage(chatId, {
        image: imageBuffer,
        caption: `🎮 *WSG - Would You Rather Game*\n\n🤔 ${randomQuestion}\n\n💭 Reply with your choice!`
    }, { quoted: message });
}
 
module.exports = wsgCommand;